ALTER TABLE items ADD COLUMN supplier TEXT;
ALTER TABLE items ADD COLUMN product_code TEXT;
ALTER TABLE items ADD COLUMN unit TEXT;
ALTER TABLE items ADD COLUMN min_qty INTEGER NOT NULL DEFAULT 0;
ALTER TABLE items ADD COLUMN pinned INTEGER NOT NULL DEFAULT 0;
