CREATE TABLE IF NOT EXISTS stores (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL UNIQUE,
  active INTEGER NOT NULL DEFAULT 1,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT OR IGNORE INTO stores (id, name) VALUES (1, 'Main Store');

ALTER TABLE users ADD COLUMN store_id INTEGER NOT NULL DEFAULT 1;

CREATE TABLE IF NOT EXISTS store_item_qty (
  store_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  current_qty INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (store_id, item_id)
);

CREATE TABLE IF NOT EXISTS store_inventory_records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  store_id INTEGER NOT NULL,
  record_date TEXT NOT NULL,
  weekday INTEGER NOT NULL,
  note TEXT,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(store_id, record_date)
);

CREATE TABLE IF NOT EXISTS store_inventory_record_items (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  record_id INTEGER NOT NULL,
  item_id INTEGER NOT NULL,
  qty INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(record_id, item_id)
);

ALTER TABLE pos_sales ADD COLUMN store_id INTEGER NOT NULL DEFAULT 1;
